# Generated by Django 5.0.4 on 2024-04-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduledEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("title", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("scheduled_datetime", models.DateTimeField()),
            ],
        ),
    ]
